//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTLONLTWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ImageDetails = new HashSet<ImageDetail>();
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public string IdProduct { get; set; }
        public string NameProduct { get; set; }
        public string IdCatalog { get; set; }
        public string IdBrand { get; set; }
        public double Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> Discount { get; set; }
        public string Description { get; set; }
        public string State { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Catalog Catalog { get; set; }
        public virtual ICollection<ImageDetail> ImageDetails { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
