//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTLONLTWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public string IdUser { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string Password { get; set; }
        public string Gender { get; set; }
        public string IdAvatar { get; set; }
        public string Address { get; set; }
        public string Member { get; set; }
        public Nullable<double> TotalSpent { get; set; }
        public string TypeUser { get; set; }
        public string Receiver { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
